services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: joedayz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres